In [2]:
import polars as pl

In [3]:
df = pl.read_csv("../TradingAgents/results/event_studies/event_study_metrics.csv")

In [14]:
df

shape: (180, 9)
┌─────────────┬─────────────┬────────┬────────┬───┬────────┬─────────────┬────────────┬────────────┐
│ Event       ┆ Strategy    ┆ Return ┆ Sharpe ┆ … ┆ Calmar ┆ CAPM Alpha  ┆ FF3 Alpha  ┆ FF5 Alpha  │
│ ---         ┆ ---         ┆ ---    ┆ Ratio  ┆   ┆ Ratio  ┆ (Ann)       ┆ (Ann)      ┆ (Ann)      │
│ str         ┆ str         ┆ f64    ┆ ---    ┆   ┆ ---    ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆        ┆ f64    ┆   ┆ f64    ┆ f64         ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪════════╪════════╪═══╪════════╪═════════════╪════════════╪════════════╡
│ COVID-19    ┆ Zero-View   ┆ 10.32  ┆ 0.419  ┆ … ┆ 0.511  ┆ 8.65        ┆ 11.64      ┆ 15.63      │
│ Crash &     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Rebound     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ COVID-19    ┆ Human-BL    ┆ 12.36  ┆ 0.484  ┆ … ┆ 0.649  ┆ 11.09       ┆ 14.33      ┆ 18.49      │
│ Crash &     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Rebound     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ COVID-19    ┆ LLM-BL-A    ┆ 0.43   ┆ 0.04   ┆ … ┆ 0.018  ┆ -5.4        ┆ -4.9       ┆ -0.64      │
│ Crash &     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Rebound     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ COVID-19    ┆ LLM-BL-B    ┆ -2.95  ┆ -0.119 ┆ … ┆ -0.119 ┆ -9.02       ┆ -8.4       ┆ -6.27      │
│ Crash &     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Rebound     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ COVID-19    ┆ LLM-BL-C    ┆ -0.76  ┆ 0.032  ┆ … ┆ -0.032 ┆ -6.0        ┆ -4.44      ┆ -2.59      │
│ Crash &     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Rebound     ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ …           ┆ …           ┆ …      ┆ …      ┆ … ┆ …      ┆ …           ┆ …          ┆ …          │
│ Regional    ┆ Endowus_Act ┆ 0.04   ┆ -0.178 ┆ … ┆ 0.009  ┆ -3.1        ┆ -2.8       ┆ -2.84      │
│ Banking     ┆ ual_20/80   ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Crisis      ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Regional    ┆ Endowus_Act ┆ 0.79   ┆ 0.058  ┆ … ┆ 0.162  ┆ -1.78       ┆ -1.25      ┆ -1.38      │
│ Banking     ┆ ual_40/60   ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Crisis      ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Regional    ┆ Endowus_Act ┆ 1.59   ┆ 0.208  ┆ … ┆ 0.28   ┆ -0.58       ┆ 0.17       ┆ -0.04      │
│ Banking     ┆ ual_60/40   ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Crisis      ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Regional    ┆ Endowus_Act ┆ 2.3    ┆ 0.329  ┆ … ┆ 0.351  ┆ 0.83        ┆ 1.82       ┆ 1.52       │
│ Banking     ┆ ual_80/20   ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Crisis      ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Regional    ┆ Endowus_Act ┆ 3.14   ┆ 0.404  ┆ … ┆ 0.43   ┆ 2.1         ┆ 3.31       ┆ 2.92       │
│ Banking     ┆ ual_100/0   ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
│ Crisis      ┆             ┆        ┆        ┆   ┆        ┆             ┆            ┆            │
└─────────────┴─────────────┴────────┴────────┴───┴────────┴─────────────┴────────────┴────────────┘

In [12]:
df = df.with_columns(
    pl.col("Return").str.replace("%", "").cast(pl.Float64),
    pl.col("Max Drawdown").str.replace("%", "").cast(pl.Float64),
    pl.col("CAPM Alpha (Ann)").str.replace("%", "").cast(pl.Float64),
    pl.col("FF3 Alpha (Ann)").str.replace("%", "").cast(pl.Float64),
    pl.col("FF5 Alpha (Ann)").str.replace("%", "").cast(pl.Float64)
)

In [15]:

df.group_by("Strategy").agg(pl.col("Return").mean()).sort("Return", descending=True)

shape: (30, 2)
┌─────────────────────────┬───────────┐
│ Strategy                ┆ Return    │
│ ---                     ┆ ---       │
│ str                     ┆ f64       │
╞═════════════════════════╪═══════════╡
│ Human-BL                ┆ -1.058333 │
│ Zero-View               ┆ -3.373333 │
│ Endowus_Actual_100/0    ┆ -4.638333 │
│ LLM-BL-A-Monthly-Banded ┆ -4.643333 │
│ Endowus-60/40           ┆ -4.688333 │
│ …                       ┆ …         │
│ LLM-BL-B-Monthly-Banded ┆ -6.646667 │
│ LLM-BL-C                ┆ -6.745    │
│ LLM-BL-B-Banded         ┆ -6.758333 │
│ LLM-BL-D-Banded         ┆ -7.23     │
│ LLM-BL-C-Banded         ┆ -7.798333 │
└─────────────────────────┴───────────┘